services:
  secretsanta:
    build:
      context: .
      dockerfile: Dockerfile
    image: "freemantp/secretsanta:latest"
    restart: always
    ports:
      - "80:3000"
    depends_on:
      - mongodb
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/secretsanta
      - MAIL_HOST=smtp.mail.net
      - MAIL_PORT=587
      - MAIL_USER=user@mydomain.org
      - MAIL_FROM=Weihnachtswichtel <user@mydomain.org>
      - MAIL_PASSWORD=MY_PW_HERE
      - PUBLIC_BASE_URL=https://wichteln.example.com
      - ADMIN_PASSWORD_HASH=your-sha256-password-hash-here
  mongodb:
    image: "mongo:latest"
    restart: always
    volumes:
       - ./path/to/dbfolder:/data/db
    ports:
      - "27017:27017"