version: '3'
services:
  wichtelweb:
    image: "webwichtel:0.0.1"
    ports:
      - "8082:8080"
  secretsanta:
    image: "secretsanta:0.0.1"
    ports:
      - "8081:8080"
  mongodb:
    image: "mongo:latest"