services:
  frontend:
    build:
      context: .
      dockerfile: apps/frontend/Dockerfile
    image: "secretsanta-ui:latest"
    restart: always
    ports:
      - "80:80"
    environment:
      - VUE_APP_API_BASEPATH=https://wichteln.mydomain.org
  secretsanta:
    depends_on:
      - backend
  backend:
    build:
      context: .
      dockerfile: apps/backend/Dockerfile
    image: "secretsanta-api:latest"
    restart: always
    ports:
      - "8080:3000"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/secretsanta
      - MAIL_SERVER=smtp.mail.net
      - MAIL_PORT=587
      - MAIL_USE_TLS=True
      - MAIL_USERNAME=user@mydomain.org
      - MAIL_DEFAULT_SENDER=Weihnachtswichtel <user@mydomain.org>
      - MAIL_PASSWORD=MY_PW_HERE
      - SYSLOG_HOST=loghost.mydomain.org
      - SYSLOG_FORMAT=insert_syslog_format_here
      - PUBLIC_BASE_URL=https://wichteln.mydomain.org
  mongodb:
    image: "mongo:latest"
    restart: always
    volumes:
       - type: bind
         source: "/path/to/mongodbstore"
         target: "/data/db"
    ports:
      - "27017:27017"